### ISSUE TITLE
Unrecognized name: learning_rate for matrix factorization

### ISSUE THREAD

**Issue by Startouf** [kristeligt-dagblad/dbt_ml#23]
While running a matrix factorization model, I ran into the error

> Unrecognized name: learning_rate

Maybe it is related to https://github.com/kristeligt-dagblad/dbt_ml/issues/5

```
packages:
  - package: dbt-labs/dbt_utils
    version: [">=0.7.0"]
  - package: tnightengale/dbt_meta_testing
    version: [">0.3.1", "<0.4.0"]
  - package: dbt-labs/codegen
    version: [">=0.4.0", "<0.5.0"]
  - package: kristeligt-dagblad/dbt_ml
    version: 0.5.0
```
And dbt 0.20.2
