### ISSUE TITLE
dbt_ml error when creating model

### ISSUE THREAD

**Issue by michaeldfutch** [kristeligt-dagblad/dbt_ml#28]
Not sure if this is an issue or more likely user error but I’m looking into dbt_ml with bigquery and I have an error that is confusing me. I have a simple dbt model set up with this config:
```
{{
    config(
        materialized='model',
        ml_config={
            'model_type': 'logistic_reg',
            'auto_class_weights':true,
            'input_label_cols':['dep_var']
        }
    )
}}
```
The select statement just has the dep_var and 8 floats. When I try to dbt run -s model_name  I get this error:

```Query column 6 has type ARRAY<STRUCT<class_label STRING, processed_input STRING, weight FLOAT64, ...>> which cannot be inserted into column weights, which has type ARRAY<STRUCT<processed_input STRING, weight FLOAT64, category_weights ARRAY<STRUCT<category STRING, weight FLOAT64>>>> at [6:5]```

however, when I take the compiled code out of the run folder, it works just fine.  Any thoughts?
Here’s the relevant portions of my project yaml:
```
vars:

  "dbt_ml:audit_schema": "data_science"
  "dbt_ml:audit_table": "ml_models"


on-run-start:
  - "{{ dbt_ml.create_model_audit_table() }}"

models:
  dbt_project_name:
    +materialized: "{{ 'table' if target.name == 'prod' else 'view' }}"
    ml:
      enabled: true
      schema: ml
      materialized: model
      post-hook: "{{ dbt_ml.model_audit() }}"
```

Asked this question in dbt slack here:
https://getdbt.slack.com/archives/C024L0CBZ0B/p1646069340335279
