### ISSUE TITLE
An error has occurred when post_hook model_audit() with hyper parameter tuning 

### ISSUE THREAD

**Issue by haisland0909** [kristeligt-dagblad/dbt_ml#29]
I use dbt_ml for building kmeans model and I want to use hyper parameter tuning with model_audit.

But when I run model with such config

model config
```
ml_config={
            'model_type': 'KMEANS',
            'num_clusters': dbt_ml.hparam_range(10, 50),
            'distance_type': 'COSINE',
            'max_iterations': 10,
            'num_trials': 1
        }
```

dbt_project.yml

```
segmentation_model:
      enabled: true
      schema: ml
      materialized: model
      post-hook: "{{ dbt_ml.model_audit() }}"
```

I got error like

```
02:05:30    Invalid table-valued function ml.training_info
02:05:30    ML.TRAINING_INFO doesn't support hyperparameter tuning models. Please use ML.TRIAL_INFO instead. at [15:26]
```

It seems that we have to use ML.TRIAL_INFO for audit when hyper parameter tuning is enabled.
